
import java.util.ArrayList;

/**
 * Represents a stable or facility in the StableMate system.
 * A Stable tracks basic information such as name, acreage, costs,
 * owners, year built, and monthly income.
 */
public class Stable {
	
	private String name;
	private int acreage;
	private double monthlyCost;
	private ArrayList<Rider> owners;
	private int yearBuilt;
	private double monthlyIncome;
	
	/**
     * Creates a Stable with default values.
     * Name is left as-is (null by default), numeric fields are zero,
     * and owners are initialized as null until explicitly set.
     */
	public Stable() {
		
		this.name = name;
		this.acreage = 0;
		this.monthlyCost = 0.0;
		this.owners = null;
		this.yearBuilt = 0;
		this.monthlyIncome = 0.0;
	}
	
	/**
     * Creates a Stable with all fields specified.
     * 
     * @param name           The stable's name.
     * @param acreage        Total acreage of the property.
     * @param monthlyCost    Monthly operating cost of the stable.
     * @param owners         List of riders who own the stable.
     * @param yearBuilt      Year the stable was built.
     * @param monthlyIncome  Monthly income generated by the stable.
     */
	public Stable(String name, int acreage, double monthlyCost, ArrayList<Rider> owners, int yearBuilt, double monthlyIncome) {
		
		this.name = name;
		this.acreage = acreage;
		this.monthlyCost = monthlyCost;
		this.owners = owners;
		this.yearBuilt = yearBuilt;
		this.monthlyIncome = monthlyIncome;
	}
	
	// =======================
    //        GETTERS
    // =======================

    /**
     * Returns the stable's name.
     * 
     * @return The name of the stable.
     */
	public String getName(){ return this.name; }
	
	/**
     * Returns the size of the stable property.
     * 
     * @return The acreage value.
     */
	public int getAcreage(){ return this.acreage; }
	
	/**
     * Returns the monthly operating cost of the stable.
     * 
     * @return The monthly cost in dollars.
     */
	public double getMonthlyCost(){ return this.monthlyCost; }
	
	/**
     * Returns a copy of the list of owners associated with this stable.
     * If no owners exist, an empty list is returned.
     * 
     * @return A new list containing all owners (never null).
     */
	public ArrayList<Rider> getOwners(){ 
		
		if (owners == null) {
			return new ArrayList<Rider>();
		}
		
		return new ArrayList<Rider>(owners);
	}
	
	/**
     * Returns the year the stable was built.
     * 
     * @return Year built.
     */
	public int getYearBuilt(){ return this.yearBuilt; }
	
	/**
     * Returns the monthly income generated by the stable.
     * 
     * @return Monthly income in dollars.
     */
	public double getMonthlyIncome(){ return this.monthlyIncome; }
	
	// =======================
    //        SETTERS
    // =======================

    /**
     * Sets the stable's name.
     * 
     * @param name New stable name.
     */
	public void setName(String name){ this.name = name; }
	
	/**
     * Sets the stable's acreage.
     * 
     * @param acreage New acreage value.
     */
	public void setAcreage(int acreage){ this.acreage = acreage; }
	
	/**
     * Sets the monthly operating cost of the stable.
     * 
     * @param monthlyCost New monthly cost in dollars.
     */
	public void setMonthlyCost(double monthlyCost){ this.monthlyCost = monthlyCost; }
	
	/**
     * Sets the list of owners for this stable.
     * If the provided list is null, it is replaced with an empty list.
     * 
     * @param owners List of Rider objects representing owners.
     */
	public void setOwners(ArrayList<Rider> owners){ 
		
		if(owners == null) {
			owners = new ArrayList<Rider>();
			//Default empty list
		}
		this.owners = owners;
		}
	
	/**
     * Sets the year the stable was built.
     * 
     * @param yearBuilt New year built.
     */
	public void setYearBuilt(int yearBuilt){ this.yearBuilt = yearBuilt; }
	
	/**
     * Sets the monthly income generated by the stable.
     * 
     * @param monthlyIncome New monthly income in dollars.
     */
	public void setMonthlyIncome(double monthlyIncome){ this.monthlyIncome = monthlyIncome; }
	
	// ================
    //   OWNER HELPERS
    // ================

    /**
     * Adds a single owner to the stable's owner list.
     * If the list is currently null, it will be created.
     * 
     * @param owner Rider to add as an owner. Null values are ignored.
     */
	public void addOwner(Rider owner) {
		
		if (owner == null) {
			return;
		}
		
		if (owners == null) {
			owners = new ArrayList<Rider>();
		}
		
		owners.add(owner);
	}
	
	/**
     * Removes a specific owner from the stable's owner list.
     * If the list is null, nothing happens.
     * 
     * @param owner Rider to remove from the owner list.
     */
	public void removeOwner(Rider owner) {
		
		if (owners == null) return;
		
		owners.remove(owner);
	}
	
	/**
     * Removes all owners from the stable.
     * If the list is null, nothing happens.
     */
	public void clearOwners() {
		
		if (owners != null) {
			owners.clear();
		}
	}
	
	/**
     * Returns a formatted String representation of the Stable, including
     * name, acreage, costs, income, owners, and year built.
     * 
     * @return Human-readable stable information.
     */
	public String toString() {
		
		return "Name: " + getName() + " Acreage: " + getAcreage() + " Monthly Cost: $" + getMonthlyCost() +
		" Monthly Income: $" + getMonthlyIncome() + " Owner(s): " + getOwners() + " Year Built: " + getYearBuilt();
	}
}
